version: '3.9'

# Some basic configuration here,
# when deployed, REGISTRY_HOST should point to
# the Eureka registry service.
# The database env variables are straight forward.
#
# Since the front-end is pre-compiled, not compiled at
# runtime due to possible load-balancing issues, the
# image should be built with appropriate .env
# configuration as described below. If being deployed
# from this file, no modification should be necessary.
#
#
# IT IS IMPORTANT TO NOTE:
# This configuration is designed to be run all contained
# on a single machine. (executed by the docker.sh script)
# Any modification to this process goes beyond the
# scope of this file and care must be taken
# appropriately.

services:
  crave-mysql:
    image: mysql
    container_name: crave-mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: crave
      MYSQL_USER: Travja
      MYSQL_PASSWORD: test
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - crave

  eureka-server:
    container_name: eureka-server
    build:
      context: ./services/eureka-server
    ports:
      - 8761:8761
    expose:
      - 8761
    networks:
      - crave

  cloud-gateway:
    build:
      context: ./services/cloud-gateway
    container_name: cloud-gateway
    depends_on:
      - eureka-server
    restart: always
    ports:
      - 80:8080
    expose:
      - 8080
    environment:
      - SERVER_PORT=8080
      - REGISTRY_HOST=eureka-server:8761
      - APP_NAME=gateway-service
    networks:
      - crave

  item-service:
    build:
      context: ./services/item-service
    depends_on:
      - crave-mysql
      - eureka-server
    restart: always
#    ports:
#      - 8082:8080
    expose:
      - 8080
    env_file:
      - .env
    environment:
      - DATABASE_HOST=crave-mysql:3306
      - DATABASE_NAME=crave
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=eureka-server:8761
      - APP_NAME=item-service
    networks:
      - crave
    mem_limit: 450m
#    scale: 2

  receipt-service:
    build:
      context: ./services/receipt-service
    depends_on:
      - crave-mysql
      - eureka-server
    restart: always
    expose:
      - 8080
    env_file:
      - .env
    environment:
      - DATABASE_HOST=crave-mysql:3306
      - DATABASE_NAME=crave
      - DATABASE_USERNAME=Travja
      - DATABASE_PASSWORD=test
      - SERVER_PORT=8080
      - REGISTRY_HOST=eureka-server:8761
      - APP_NAME=receipt-service
    networks:
      - crave
    mem_limit: 450m
  #    scale: 2

# To set the gateway location used by the front-end,
# create a .env file in the base dir
# and include 'VITE_GATEWAY=uri'.
# The gateway will default to window.location.origin
# if not included.
# This would enable the front-end to run independent
# of the rest of the docker network, but still
# access the API behind the cloud gateway.
# As such, this should be the PUBLIC access point.
# No 'cloud-gateway:8080'. In a deployed scenario,
# this would not be the internal IP either. This
# would be the WAN address for the cloud gateway.
  web-server:
    build:
      context: ./web
#    container_name: web-server
    depends_on:
      - crave-mysql
      - item-service
      - cloud-gateway
      - eureka-server
    restart: always
#    env_file:
#      - .env
    environment:
      - REGISTRY_HOST=eureka-server:8761
      - SERVER_PORT=3000
      - APP_NAME=web-server
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - crave
#    scale: 2

networks:
  crave:
    name: Crave Network
